package com.smartattendance.controller;

import com.smartattendance.dto.*;import com.smartattendance.service.*;import jakarta.validation.Valid;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/users")
class UserController{private final UserService service;UserController(UserService service){this.service=service;}@GetMapping Page<UserResponse> list(@RequestParam(required=false)String q,Pageable p){return service.search(q,p);}@GetMapping("/{id}") UserResponse get(@PathVariable Long id){return service.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) UserResponse create(@Valid @RequestBody UserRequest r){return service.create(r);}@PutMapping("/{id}") UserResponse update(@PathVariable Long id,@Valid @RequestBody UserRequest r){return service.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}}

@RestController @RequestMapping("/api/students")
class StudentController{private final StudentService service;StudentController(StudentService service){this.service=service;}@GetMapping Page<StudentResponse> list(@RequestParam(required=false)String q,Pageable p){return service.search(q,p);}@GetMapping("/{id}") StudentResponse get(@PathVariable Long id){return service.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) StudentResponse create(@Valid @RequestBody StudentRequest r){return service.create(r);}@PutMapping("/{id}") StudentResponse update(@PathVariable Long id,@Valid @RequestBody StudentRequest r){return service.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}}

@RestController @RequestMapping("/api/faculty")
class FacultyController{private final FacultyService service;FacultyController(FacultyService service){this.service=service;}@GetMapping Page<FacultyResponse> list(@RequestParam(required=false)String q,Pageable p){return service.search(q,p);}@GetMapping("/{id}") FacultyResponse get(@PathVariable Long id){return service.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) FacultyResponse create(@Valid @RequestBody FacultyRequest r){return service.create(r);}@PutMapping("/{id}") FacultyResponse update(@PathVariable Long id,@Valid @RequestBody FacultyRequest r){return service.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}}

@RestController @RequestMapping("/api/courses")
class CourseController{private final CourseService service;CourseController(CourseService service){this.service=service;}@GetMapping Page<CourseResponse> list(@RequestParam(required=false)String q,Pageable p){return service.search(q,p);}@GetMapping("/{id}") CourseResponse get(@PathVariable Long id){return service.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) CourseResponse create(@Valid @RequestBody CourseRequest r){return service.create(r);}@PutMapping("/{id}") CourseResponse update(@PathVariable Long id,@Valid @RequestBody CourseRequest r){return service.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}}

@RestController @RequestMapping("/api/subjects")
class SubjectController{private final SubjectService service;SubjectController(SubjectService service){this.service=service;}@GetMapping Page<SubjectResponse> list(@RequestParam(required=false)String q,Pageable p){return service.search(q,p);}@GetMapping("/{id}") SubjectResponse get(@PathVariable Long id){return service.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) SubjectResponse create(@Valid @RequestBody SubjectRequest r){return service.create(r);}@PutMapping("/{id}") SubjectResponse update(@PathVariable Long id,@Valid @RequestBody SubjectRequest r){return service.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){service.delete(id);}}
