import { useState } from 'react';
import { api } from '../api/client.js';

export default function Reports() {
  const [filters, setFilters] = useState({ studentId: '', courseId: '', subjectId: '' });
  const [report, setReport] = useState(null);
  const load = async event => { event.preventDefault(); if (!filters.studentId) return; const { data } = await api.get(`/attendance/summary/students/${filters.studentId}`, { params: { courseId: filters.courseId || undefined, subjectId: filters.subjectId || undefined } }); setReport(data); };
  const exportCsv = async () => { const { data } = await api.get('/attendance/reports/export', { params: { studentId: filters.studentId || undefined, courseId: filters.courseId || undefined, subjectId: filters.subjectId || undefined }, responseType: 'blob' }); const url = URL.createObjectURL(data); const link = document.createElement('a'); link.href = url; link.download = 'attendance-report.csv'; link.click(); URL.revokeObjectURL(url); };
  return <section className="space-y-6"><h1 className="text-3xl font-black">Reports</h1><form onSubmit={load} className="card grid gap-4 md:grid-cols-4"><input className="input" placeholder="Student ID" value={filters.studentId} onChange={e=>setFilters({...filters,studentId:e.target.value})}/><input className="input" placeholder="Course ID" value={filters.courseId} onChange={e=>setFilters({...filters,courseId:e.target.value})}/><input className="input" placeholder="Subject ID" value={filters.subjectId} onChange={e=>setFilters({...filters,subjectId:e.target.value})}/><button className="btn">Generate</button><button type="button" className="btn md:col-span-4" onClick={exportCsv}>Admin · Export CSV Report</button></form>{report&&<article className="card max-w-xl"><h2 className="text-2xl font-bold">{report.studentName}</h2><p>Total Sessions: {report.totalSessions}</p><p>Present/Late Sessions: {report.attendedSessions}</p><p className="text-5xl font-black text-brand">{report.percentage}%</p></article>}</section>;
}
